"""Locally opt into one index motor/servo bench test; keep the VR scene unchanged."""
import argparse
from collections import OrderedDict
import hashlib
import hmac
import json
from pathlib import Path
import secrets
import socket
import struct
import time
from urllib.error import URLError
from urllib.request import ProxyHandler, build_opener

from .protocol import HEADER, VERSION, Packet, crc16, decode
from .wifi_monitor import NoRedirect, fresh, lan_ip, port_number, preview_packet, preview_values

COMMAND, RECEIPT, HELLO, HELLO_RECEIPT = 7, 8, 9, 10
BODY = struct.Struct("<IIH4B")
ACK = struct.Struct("<IIHBBHBB")
HELLO_BODY = struct.Struct("<I")
HELLO_ACK = struct.Struct("<II")
DOMAIN = b"AHAM-BENCH-v1"
TAG_SIZE = 16
REASONS = ("BOOT", "READY", "MANUAL_STOP", "STOP_OPEN", "LINK_LOST", "ARM_EXPIRED",
           "PULL_EXPIRED", "I2C_FAULT", "SESSION_CHANGED")


def signed(kind, sequence, now_ms, body, key):
    header = HEADER.pack(VERSION, kind, sequence & 0xffff, now_ms & 0xffffffff)
    tag = hmac.new(key, DOMAIN + header + body, hashlib.sha256).digest()[:TAG_SIZE]
    return Packet(kind, sequence, now_ms, body + tag)


def authenticated(packet, body_size, key):
    if len(packet.payload) != body_size + TAG_SIZE:
        raise ValueError("Wrong authenticated packet size")
    body = packet.payload[:body_size]
    expected = signed(packet.kind, packet.sequence, packet.time_ms, body, key).payload[-TAG_SIZE:]
    if not hmac.compare_digest(expected, packet.payload[-TAG_SIZE:]):
        raise ValueError("Packet authentication failed")
    return body


def command_packet(snapshot, session, boot, sequence, now_ms, key, elapsed=0):
    if not 1 <= boot <= 0xffffffff:
        raise ValueError("A fresh ESP boot nonce is required")
    # Tighten the observation monitor's 500 ms grip freshness to 250 ms for bench motion.
    if isinstance(snapshot, dict) and not fresh(snapshot.get("grip"), 250, elapsed):
        snapshot = dict(snapshot, grip=None)
    values = preview_values(preview_packet(snapshot, session, sequence, now_ms, elapsed))
    # Existing freshness/tracking checks run BEFORE selecting only the index slot.
    body = BODY.pack(session, boot, 250, values["flags"], values["vibration"][1],
                     values["patterns"][1], values["resistance"][1])
    return signed(COMMAND, sequence, now_ms, body, key)


def read_key(path):
    try:
        value = bytes.fromhex(Path(path).read_text(encoding="ascii").strip())
        if len(value) != 32 or not any(value):
            raise ValueError()
        return value
    except (OSError, ValueError, UnicodeError):
        raise ValueError("Use the private .key file generated by tools/setup_wifi_bench.py") from None


class WirelessBench:
    def __init__(self, address, key, session=None):
        if len(key) != 32 or not any(key):
            raise ValueError("A nonzero 32-byte pairing key is required")
        self.key = key
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.connect(address)
        self.socket.setblocking(False)
        self.session = session or secrets.randbits(32) or 1
        self.boot = 0
        self.sequence = 0
        self.pending = OrderedDict()
        self.last_receipt = None
        self.last_hello = -10.0
        self.received = 0

    def send(self, snapshot, elapsed=0):
        now = time.monotonic()
        self._prune(now)
        # Repeat handshake to discover a reboot. Hello cannot arm the ESP.
        if now - self.last_hello >= 1:
            hello = signed(HELLO, self.sequence, int(now*1000), HELLO_BODY.pack(self.session), self.key)
            self._send(hello, now)
            self.last_hello = now
        if self.boot:
            packet = command_packet(snapshot, self.session, self.boot, self.sequence, int(now*1000), self.key, elapsed)
            self._send(packet, now)
            return packet
        return None

    def _send(self, packet, now):
        self.socket.send(packet.encode())
        self.pending[packet.sequence] = (now, packet)
        self.sequence = (self.sequence+1) & 0xffff

    def _prune(self, now):
        while self.pending and (len(self.pending) > 32 or now-next(iter(self.pending.values()))[0] >= .5):
            self.pending.popitem(last=False)

    def poll(self):
        now = time.monotonic()
        self._prune(now)
        for _ in range(16):
            try:
                frame = self.socket.recv(128)
            except (BlockingIOError, ConnectionResetError):
                break
            try:
                ack = decode(frame)
                pending = self.pending.get(ack.sequence)
                if pending is None:
                    continue
                packet = pending[1]
                if ack.kind == HELLO_RECEIPT and packet.kind == HELLO:
                    session, boot = HELLO_ACK.unpack(authenticated(ack, HELLO_ACK.size, self.key))
                    if session != self.session or not boot:
                        continue
                    if boot != self.boot:
                        self.boot = boot
                        self.last_receipt = None
                        self.pending.clear()
                    else:
                        self.pending.pop(ack.sequence)
                    continue
                if ack.kind != RECEIPT or packet.kind != COMMAND:
                    continue
                session, boot, checksum, armed, pwm, pulse, enabled, reason = ACK.unpack(
                    authenticated(ack, ACK.size, self.key))
                if (session != self.session or boot != self.boot or checksum != crc16(packet.payload[:BODY.size])
                        or armed > 3 or pwm > 160 or not 1400 <= pulse <= 1600 or enabled > 1
                        or reason >= len(REASONS) or (not armed & 1 and pwm)):
                    continue
                if self.last_receipt:
                    advance = (ack.sequence-self.last_receipt["sequence"]) & 0xffff
                    if not 0 < advance < 0x8000:
                        continue  # An older ACK must not overwrite a newer STOP report.
                values = BODY.unpack(packet.payload[:BODY.size])
            except (ValueError, struct.error):
                continue
            self.pending.pop(ack.sequence)
            self.received += 1
            self.last_receipt = dict(sequence=ack.sequence, receivedAt=now, vibration=values[4],
                                     resistance=values[6], holding=bool(values[3] & 2), armed=armed,
                                     pwm=pwm, servoUs=pulse, servoSignal=bool(enabled), reason=REASONS[reason])
        return self.last_receipt if self.last_receipt and now-self.last_receipt["receivedAt"] < .5 else None

    def close(self):
        try:
            if self.boot:
                for _ in range(3):
                    self.send(None)
        except OSError:
            pass
        finally:
            self.socket.close()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--esp-ip", type=lan_ip, required=True)
    parser.add_argument("--esp-port", type=port_number, default=4211)
    parser.add_argument("--relay-port", type=port_number, default=8890)
    parser.add_argument("--key-file", type=Path, required=True)
    args = parser.parse_args()
    try:
        key = read_key(args.key_file)
    except ValueError as error:
        parser.error(str(error))
    bench = WirelessBench((args.esp_ip, args.esp_port), key)
    opener = build_opener(ProxyHandler({}), NoRedirect())
    url = f"http://127.0.0.1:{args.relay_port}/api/wifi-preview"
    print("AHAM INDEX BENCH: local opt-in; only second/index values forwarded. ESP boots DISARMED.", flush=True)
    print("Detached thread first. Serial 115200 + newline: ARM MOTOR / ARM SERVO / ARM BOTH / STOP.", flush=True)
    print("PWM and servo pulses confirm software output commands, not actual vibration, motion or tension.", flush=True)
    last_print = 0
    try:
        while True:
            started = time.monotonic()
            snapshot = None
            try:
                with opener.open(url, timeout=.15) as response:
                    body = response.read(8193)
                    if len(body) > 8192:
                        raise ValueError("Oversized preview")
                    snapshot = json.loads(body)
            except (OSError, URLError, ValueError, RecursionError):
                pass
            try:
                bench.send(snapshot, time.monotonic()-started)
                receipt = bench.poll()
            except OSError:
                receipt = None
            now = time.monotonic()
            if now-last_print >= .5:
                last_print = now
                if receipt:
                    print(f"ESP INDEX seq={receipt['sequence']} VIB={receipt['vibration']} RES%={receipt['resistance']} "
                          f"HOLD={receipt['holding']} ARMED={receipt['armed']} PWM={receipt['pwm']} "
                          f"SERVO_US={receipt['servoUs']} SIGNAL={receipt['servoSignal']} {receipt['reason']}", flush=True)
                else:
                    print("NO FRESH BENCH RECEIPT: check new firmware, IPs, pairing key and UDP 4211.", flush=True)
                if snapshot is None:
                    print("Relay unavailable: sending zeros.", flush=True)
            time.sleep(max(0, .05-(time.monotonic()-started)))
    except KeyboardInterrupt:
        pass
    finally:
        bench.close()


if __name__ == "__main__":
    main()
