"""Export the existing NodeMCU firmware as an Arduino IDE sketch and bundle it."""
from pathlib import Path
import zipfile

root = Path(__file__).resolve().parents[1]
sketch = root / 'firmware' / 'arduino' / 'AhamIndex'
sketch.mkdir(parents=True, exist_ok=True)
banner = (
    '// AHAM index-finger firmware for ESP8266 NodeMCU, Arduino core 3.1.2.\n'
    '// Generated by tools/package_index_arduino.py from firmware/src/main.cpp.\n'
    '// Open this sketch with its three .h files in the same folder.\n'
    '#if !defined(ESP8266)\n'
    '#error "Select NodeMCU 1.0 (ESP-12E Module), not an ESP32 board."\n'
    '#endif\n'
)
(sketch / 'AhamIndex.ino').write_text(
    banner + (root / 'firmware' / 'src' / 'main.cpp').read_text(), encoding='utf-8'
)
for name in ['AhamProtocol.h', 'ActuatorSupervisor.h', 'BoardConfig.h']:
    (sketch / name).write_text(
        (root / 'firmware' / 'include' / name).read_text(), encoding='utf-8'
    )

output = root / 'artifacts' / 'AHAM-Index-Arduino.zip'
with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED) as archive:
    for folder in [sketch, root / 'firmware' / 'arduino' / 'FlexCheck']:
        for path in sorted(folder.iterdir()):
            if path.is_file():
                archive.write(path, path.relative_to(root / 'firmware' / 'arduino'))
    archive.write(root / 'docs' / 'index-finger-step-by-step.md', 'START-HERE.md')
    archive.write(root / 'docs' / 'index-finger-mvp.md', 'index-finger-mvp.md')
    archive.write(root / 'docs' / 'hardware-bringup.md', 'hardware-bringup.md')
print(output)
