[platformio]
default_envs = nodemcuv2

[env]
framework = arduino
build_flags = -Wall -Wextra
build_src_filter = +<main.cpp>
monitor_speed = 230400

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2

[env:nodemcu_probe]
platform = espressif8266@4.2.1
board = nodemcuv2
build_src_filter = +<probe.cpp>
monitor_speed = 115200

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
